INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:06:27] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:06:27] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:09:32] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:09:32] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:09:33] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:09:40] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:09:40] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:09:41] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:09:41] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:09:57] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:09:57] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:09:57] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:09:58] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:10:12] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:10:12] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:12:19] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:13:32] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:13:32] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:14:08] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:14:08] "POST /find HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:15:16] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:15:16] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:15:17] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:16:38] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    rv = jsonify(rv)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/yancarlos/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:16:38] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:19:22] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:19:22] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:19:28] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:19:28] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:19:33] "POST /find HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:21:30] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:21:30] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:21:32] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:08] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:08] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:09] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:10] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:11] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:11] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:51] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:51] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:52] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:54] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:55] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:59] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:22:59] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:23:00] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:23:00] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:23:00] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:23:00] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 39, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:23:03] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:24:46] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:24:46] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:24:46] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:24:55] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:24:55] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:26:40] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:26:40] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:26:41] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:26:41] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:26:41] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:27:48] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:27:48] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:28:09] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 160, in similarity
    docs = q.get_documents(self.files)
AttributeError: 'NoneType' object has no attribute 'get_documents'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:28:09] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:29:43] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 160, in similarity
    docs = q.get_documents(self.files)
AttributeError: 'NoneType' object has no attribute 'get_documents'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:29:43] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 160, in similarity
    docs = q.get_documents(self.files)
AttributeError: 'NoneType' object has no attribute 'get_documents'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:29:45] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 160, in similarity
    docs = q.get_documents(self.files)
AttributeError: 'NoneType' object has no attribute 'get_documents'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:29:45] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 160, in similarity
    docs = q.get_documents(self.files)
AttributeError: 'NoneType' object has no attribute 'get_documents'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:29:45] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:30:04] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:30:04] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:30:05] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:30:05] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:30:26] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:30:26] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:30:29] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:30:53] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:30:53] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:30:54] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:31:06] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:31:06] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:31:07] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 40, in find
    data = {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:31:08] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:32:14] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:32:14] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:33:12] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:33:12] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:33:14] "POST /find HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:33:43] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 42, in find
    "data": {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:33:43] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 42, in find
    "data": {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:33:46] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 42, in find
    "data": {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:33:47] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:34:01] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 42, in find
    "data": {
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:34:01] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:35:45] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:35:45] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:38:11] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:38:11] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:38:13] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:38:19] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:38:19] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:38:32] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:38:32] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:38:32] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:38:33] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:39:00] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:39:00] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:39:24] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:39:24] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:39:25] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:39:25] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:40:10] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 160, in similarity
    docs = q.get_documents(self.files)
AttributeError: 'NoneType' object has no attribute 'get_documents'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:40:10] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:40:14] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:40:15] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:40:15] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:40:51] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4.zip/omw-1.4/[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/vectorial.py", line 73, in similarity
    return doc_rank[:k], expand(self, query_token)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Improvement/query_expansion.py", line 11, in expand
    for syn in wn.synsets(query[i]):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93momw-1.4[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('omw-1.4')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/omw-1.4[0m

  Searched in:
    - '/Users/yancarlos/nltk_data'
    - '/Users/yancarlos/miniforge3/nltk_data'
    - '/Users/yancarlos/miniforge3/share/nltk_data'
    - '/Users/yancarlos/miniforge3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:40:51] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:44:31] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 21:46:01] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:01:16] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:02:27] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:03:07] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:03:07] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:04:20] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:04:20] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:04:56] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:04:56] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:05:12] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:05:12] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:07:01] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:07:01] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:07:31] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:07:32] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:08:58] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:08:58] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:12:53] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:12:53] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:12:57] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:13:04] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:13:04] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:13:13] "OPTIONS /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2022 22:13:13] "POST /download HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:23:20] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:23:20] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:23:21] "OPTIONS /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:23:21] "POST /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:23:27] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:23:28] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:23:28] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:23:31] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:23:43] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 166, in similarity
    if q.error:
AttributeError: 'TOKEN' object has no attribute 'error'
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:23:43] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 166, in similarity
    if q.error:
AttributeError: 'TOKEN' object has no attribute 'error'
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:23:45] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:24:00] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 166, in similarity
    if q.error:
AttributeError: 'TOKEN' object has no attribute 'error'
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:24:00] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:24:13] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 166, in similarity
    if q.error:
AttributeError: 'TOKEN' object has no attribute 'error'
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:24:13] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 166, in similarity
    if q.error:
AttributeError: 'TOKEN' object has no attribute 'error'
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:24:14] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:24:49] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 166, in similarity
    if q.error:
AttributeError: 'TOKEN' object has no attribute 'error'
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:24:49] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:24:56] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 166, in similarity
    if q.error:
AttributeError: 'TOKEN' object has no attribute 'error'
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:24:56] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:28:14] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 167, in similarity
    if q.error:
AttributeError: 'TOKEN' object has no attribute 'error'
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:28:14] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:28:26] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 167, in similarity
    if q.error:
AttributeError: 'TOKEN' object has no attribute 'error'
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:28:26] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:28:44] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 167, in similarity
    if q.error:
AttributeError: 'AND' object has no attribute 'error'
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:28:44] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:30:20] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 167, in similarity
AttributeError: 'AND' object has no attribute 'error'
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:30:20] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:30:53] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:30:53] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:31:03] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:31:03] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:31:16] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:31:16] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:31:40] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:31:40] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:34:01] "OPTIONS /find HTTP/1.1" 200 -
ERROR:main:Exception on /find [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 36, in find
    response, expand = find_service.find(query, count)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/find_services.py", line 10, in find
    return self.model.similarity(query, k)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 164, in similarity
    q = self.query_parser(query)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 160, in query_parser
    tree = q_parser.run(query)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 104, in run
    ast = self.parser.parse(input=query, lexer=self.lexer.lexer)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/ply/lex.py", line 350, in token
    newtok = func(tok)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/Model/boolean.py", line 85, in t_TOKEN
    t.value = tokenizer(t.value)[0]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:34:01] "[35m[1mPOST /find HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:36:12] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:36:12] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:36:39] "OPTIONS /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:36:39] "POST /download HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:52:08] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:52:08] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:52:21] "OPTIONS /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:52:21] "POST /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:52:22] "POST /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:52:27] "OPTIONS /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:52:27] "POST /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:52:28] "POST /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:52:29] "POST /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:53:16] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:53:16] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:54:24] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:54:24] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:54:29] "OPTIONS /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:54:29] "POST /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:54:31] "POST /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:54:32] "POST /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:54:33] "POST /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:54:34] "POST /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:54:50] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:54:50] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:54:54] "OPTIONS /download HTTP/1.1" 200 -
ERROR:main:Exception on /download [POST]
Traceback (most recent call last):
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/main.py", line 55, in download
    download_file = FileService.download(PATHS[0] + '/' + file)
  File "/Users/yancarlos/Documents/Escuela/5to/SRI/backend/src/services/file_service.py", line 7, in download
    return send_file(file_name, as_attachment=True)
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/flask/helpers.py", line 610, in send_file
    return werkzeug.utils.send_file(
  File "/Users/yancarlos/miniforge3/lib/python3.9/site-packages/werkzeug/utils.py", line 440, in send_file
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/yancarlos/Documents/Escuela/5to/SRI/backend/public/files/104259'
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:54:54] "[35m[1mPOST /download HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:55:04] "OPTIONS /download HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 09:55:04] "POST /download HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:05:23] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:05:23] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:05:50] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:05:51] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:04] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:04] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:09] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:09] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:16] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:16] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:18] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:19] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:26] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:26] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:28] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:35] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:35] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:37] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:44] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:06:44] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:07:12] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:07:13] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:07:33] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:07:33] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:07:34] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:07:41] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:07:41] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:07:51] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:07:51] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:08:04] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:08:04] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:08:11] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:08:11] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:08:15] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:08:19] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:08:19] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:08:23] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:08:29] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:08:29] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:08:45] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:08:45] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:09:41] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:09:41] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:09:50] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:09:50] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:10:17] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:10:18] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:10:22] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:10:40] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:10:40] "POST /find HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:24:45] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:24:45] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:24:55] "OPTIONS /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:24:56] "POST /find HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Jun/2022 10:24:59] "POST /find HTTP/1.1" 200 -
